# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  rtl8851bu = config.boot.kernelPackages.callPackage (
    {
      stdenv,
      fetchFromGitHub,
      kernel,
      bc,
      ...
    }:
    stdenv.mkDerivation {
      pname = "rtl8851bu";
      version = "v1.19.10";

      src = fetchFromGitHub {
        owner = "fofajardo";
        repo = "rtl8851bu";
        rev = "1f1a14492fdac757c64a7efb7846be6374984d09"; # Фіксована версія для стабільності
        sha256 = "sha256-DohgeyAz3Op7Al5rHHMs4ZAQuTVJxOFRLx6BqzYwE7I=";
      };

      nativeBuildInputs = [ bc ];
      hardeningDisable = [ "pic" ];

      makeFlags = [
        "ARCH=x86_64"
        "KSRC=${kernel.dev}/lib/modules/${kernel.modDirVersion}/build"
        "INSTALL_MOD_PATH=$(out)"
      ];

      prePatch = ''
        substituteInPlace Makefile --replace "-Werror" ""
      '';

      installPhase = ''
        mkdir -p $out/lib/modules/${kernel.modDirVersion}/kernel/drivers/net/wireless/realtek/rtl8851bu
        install -m 644 8851bu.ko $out/lib/modules/${kernel.modDirVersion}/kernel/drivers/net/wireless/realtek/rtl8851bu
      '';
    }
  ) { };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "8851bu"
  ];
  boot.extraModulePackages = [ rtl8851bu ];

  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="0bda", ATTR{idProduct}=="1a2b", RUN+="${pkgs.usb-modeswitch}/bin/usb_modeswitch -K -v 0bda -p 1a2b"
  '';
  
  hardware.bluetooth.enable = true;
  hardware.usb-modeswitch.enable = true;

  services.tlp = import ./tlp.nix;

  fileSystems."/" = {
    device = "zroot/root";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/nix" = {
    device = "zroot/nix";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/var" = {
    device = "zroot/var";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/home" = {
    device = "zroot/home";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/mnt/tank/steam" = {
    device = "tank/steam";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/mnt/tank/games" = {
    device = "tank/games";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/mnt/tank/data" = {
    device = "tank/data";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-id/nvme-WD_Blue_SN580_1TB_25020N801835-part1";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-id/nvme-WD_Blue_SN580_1TB_25020N801835-part3"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
