# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."excalidraw" = {
    image = "excalidraw/excalidraw:latest";
    environment = {
      "NODE_ENV" = "production";
      "VITE_APP_WS_SERVER_URL" = "https://board.azazak123.dedyn.io";
    };
    ports = [
      "127.0.0.1:8080:80/tcp"
    ];
    cmd = [ "-c" "echo \"Replacing WebSocket URL with: $VITE_APP_WS_SERVER_URL\"
  find /usr/share/nginx/html/assets -type f -name \"*.js\" -exec sed -i 's|https://oss-collab\\.excalidraw\\.com|'$VITE_APP_WS_SERVER_URL'|g' {} +
  echo \"Starting nginx...\"
  nginx -g 'daemon off;'
  " ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=CHOWN"
      "--cap-add=SETGID"
      "--cap-add=SETUID"
      "--cap-add=NET_BIND_SERVICE"
      "--cap-drop=ALL"
      "--entrypoint=[\"/bin/sh\"]"
      "--health-cmd=wget -qO- http://127.0.0.1:80/ >/dev/null 2>&1 || exit 1"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=excalidraw"
      "--network=excalidraw_default"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."podman-excalidraw" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-excalidraw_default.service"
    ];
    requires = [
      "podman-network-excalidraw_default.service"
    ];
    partOf = [
      "podman-compose-excalidraw-root.target"
    ];
    wantedBy = [
      "podman-compose-excalidraw-root.target"
    ];
  };
  virtualisation.oci-containers.containers."excalidraw-room" = {
    image = "excalidraw/excalidraw-room:latest";
    ports = [
      "127.0.0.1:8081:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-drop=ALL"
      "--cap-add=NET_BIND_SERVICE"
      "--health-cmd=wget -qO- http://127.0.0.1:80/ >/dev/null 2>&1 || exit 1"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=excalidraw-room"
      "--network=excalidraw_default"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."podman-excalidraw-room" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-excalidraw_default.service"
    ];
    requires = [
      "podman-network-excalidraw_default.service"
    ];
    partOf = [
      "podman-compose-excalidraw-root.target"
    ];
    wantedBy = [
      "podman-compose-excalidraw-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-excalidraw_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f excalidraw_default";
    };
    script = ''
      podman network inspect excalidraw_default || podman network create excalidraw_default
    '';
    partOf = [ "podman-compose-excalidraw-root.target" ];
    wantedBy = [ "podman-compose-excalidraw-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-excalidraw-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
